# Generated by Django 5.1.7 on 2025-03-31 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('original_image', models.ImageField(upload_to='originals/', verbose_name='Image originale')),
                ('bead_pattern', models.ImageField(blank=True, upload_to='patterns/', verbose_name='Motif en perles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('grid_size', models.IntegerField(default=32, verbose_name='Taille de la grille')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Modèle de perles',
                'verbose_name_plural': 'Modèles de perles',
                'ordering': ['-created_at'],
            },
        ),
    ]
