# Generated by Django 5.1.7 on 2025-03-31 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beadmodels', '0002_customshape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeadShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('shape_type', models.CharField(choices=[('rectangle', 'Rectangle'), ('square', 'Carré'), ('circle', 'Rond')], max_length=20, verbose_name='Type de forme')),
                ('width', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Largeur')),
                ('height', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hauteur')),
                ('size', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taille')),
                ('diameter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Diamètre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_default', models.BooleanField(default=False, verbose_name='Forme par défaut')),
            ],
            options={
                'verbose_name': 'Forme de perles',
                'verbose_name_plural': 'Formes de perles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='customshape',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Forme personnalisée', 'verbose_name_plural': 'Formes personnalisées'},
        ),
        migrations.AlterField(
            model_name='customshape',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='diameter',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Diamètre'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='shape_type',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('square', 'Carré'), ('circle', 'Rond')], max_length=20, verbose_name='Type de forme'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_shapes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='customshape',
            name='width',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Largeur'),
        ),
        migrations.AddField(
            model_name='customshape',
            name='base_shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beadmodels.beadshape', verbose_name='Forme de base'),
        ),
    ]
