# Generated by Django 5.1.7 on 2025-04-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beadmodels", "0002_add_default_boards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customshape",
            name="base_shape",
        ),
        migrations.AlterUniqueTogether(
            name="customshape",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="customshape",
            name="user",
        ),
        migrations.DeleteModel(
            name="BeadShape",
        ),
        migrations.DeleteModel(
            name="CustomShape",
        ),
    ]
