# Generated by Django 5.2.8 on 2025-11-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beadmodels", "0005_beadmodel_metadata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bead",
        ),
    ]
