# Generated by Django 5.1.7 on 2025-06-13 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shapes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beadshape",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="beadshape",
            name="is_shared",
        ),
    ]
