# Generated by Django 5.1.7 on 2025-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shapes", "0002_remove_beadshape_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beadshape",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Forme par défaut"),
        ),
        migrations.AddField(
            model_name="beadshape",
            name="is_shared",
            field=models.BooleanField(default=False, verbose_name="Forme partagée"),
        ),
    ]
