# Generated by Django 5.1.7 on 2025-09-11 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shapes", "0003_beadshape_is_default_beadshape_is_shared"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="beadshape",
            index=models.Index(
                fields=["creator"], name="shapes_bead_creator_8a603e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beadshape",
            index=models.Index(
                fields=["shape_type"], name="shapes_bead_shape_t_b16915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beadshape",
            index=models.Index(
                fields=["is_default"], name="shapes_bead_is_defa_9f890c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beadshape",
            index=models.Index(
                fields=["is_shared"], name="shapes_bead_is_shar_a745b5_idx"
            ),
        ),
    ]
