# Generated by Django 5.2.8 on 2026-02-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shapes", "0004_beadshape_shapes_bead_creator_8a603e_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomShape",
        ),
    ]
